portcalls:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', '../data/warehouse.duckdb') }}"
      extensions: [spatial]
      threads: 1
      settings:
        memory_limit: "3GB"
        threads: 2
        preserve_insertion_order: false
